require 'gosu'

module Settings
  SCREEN_WIDTH = 320
  SCREEN_HEIGHT = 480
  OFF_SCREEN_Y = -300
  TILE_GAP = 2
  FPS = 30
  BOUNCE_FPS = 60
  BOUNCE_DURATION = 3000
  OBSTACLE_STATE = %i[NONE GLASS WOOD CEMENT].freeze
  SWEET_TREATS = %i[MINT_SWEET PURPLE_SWEET GOBSTOPPER COOKIE].freeze
end
