Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 15

Metrics/MethodLength:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 700

Metrics/ModuleLength:
  Max: 700

Metrics/PerceivedComplexity:
  Max: 20
